# creating k8s the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app
spec:
  replicas: 3
  selector:
    matchLabels:
      custom: app
  template:
    metadata:
      labels:
        custom: app
    spec:
      containers:
      - name: custom-app
        image: nginx
        ports:
        - containerPort: 80