# Ingress resource for routing external traffic to the custom-app-service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt    
spec:
  ingressClassName: nginx
  rules:
    - host: custom-app.buildverse.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: custom-app-service
                port: 
                  number: 80
  tls:
  - hosts:
    - custom-app.buildverse.site
    secretName: custom-app-ssl-secret  
