# exposing the deployment
apiVersion: v1
kind: Service
metadata:
  name: custom-app-service
spec:
  selector:
    custom: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP